### PR TITLE
docs(readme): remove install when using yarn add

### PR DESCRIPTION
**Pull request by ilmxml**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case
You don't need to “install” when using yarn add

### CODE REVIEW

**Review by snitin315 — APPROVED** [review]

**Comment by snitin315** [comment]
@ilmxml Can you accept CLA?

**Comment by ilmxml** [comment]
> @ilmxml Can you accept CLA?

Yes，just a moment, I will sign it

**Comment by ilmxml** [comment]
> @ilmxml Can you accept CLA?

I changed my account now and signed up for the CLA, wating for approve😊

**Comment by ricardogobbosouza** [comment]
Thanks @ilmxml

**Pull request merged**
