### PR TITLE
fix: crash on `split`

### LINKED ISSUE #61: TypeError: Cannot read property 'split' of undefined
- Operating System: Mac os
- Node Version: v12.14.1
- Yarn Version: 1.22.5
- webpack Version: 
- eslint-webpack-plugin Version:
Not too sure what webpack version I'm using as it's bootstrapped using vue-cli tools.
```
  "dependencies": {
    "@fullstory/browser": "^1.4.6",
    "@funnel-io/nav-plugin-api": "^1.9.0",
    "core-js": "^3.6.5",
    "git-describe": "^4.0.4",
    "vue": "3.0.5"
  },
  "devDependencies": {
    "@sentry/webpack-plugin": "^1.14.0",
    "@typescript-eslint/eslint-plugin": "^4.9.1",
    "@typescript-eslint/parser": "^4.9.1",
    "@vue/cli-plugin-babel": "^5.0.0-alpha.2",
    "@vue/cli-plugin-eslint": "^5.0.0-alpha.2",
    "@vue/cli-plugin-typescript": "^5.0.0-alpha.2",
    "@vue/cli-service": "^5.0.0-alpha.2",
    "@vue/compiler-sfc": "^3.0.0-beta.1",
    "@vue/eslint-config-typescript": "^7.0.0",
    "eslint": "^7.15.0",
    "eslint-plugin-vue": "7.3.0",
    "typescript": "^4.1.3"
  }
```

### Stacktrace

```
lilja in ~/c/u/customs-data-form on typescript λ make serve
yarn run serve
yarn run v1.22.5
warning ../../package.json: No license field
$ vue-cli-service serve
 INFO  Starting development server...
10% building 0/6 entries 2/6 dependencies 0/1 modules/Users/lilja/code/umbrella/customs-data-form/node_modules/eslint-webpack-plugin/dist/index.js:93
        const file = module.resource.split('?')[0];
                                     ^

TypeError: Cannot read property 'split' of undefined
    at processModule (/Users/lilja/code/umbrella/customs-data-form/node_modules/eslint-webpack-plugin/dist/index.js:93:38)
    at Hook.eval [as call] (eval at create (/Users/lilja/code/umbrella/customs-data-form/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at /Users/lilja/code/umbrella/customs-data-form/node_modules/webpack/lib/Compilation.js:1262:33
    at /Users/lilja/code/umbrella/customs-data-form/node_modules/webpack/lib/HookWebpackError.js:69:3
    at Hook.eval [as callAsync] (eval at create (/Users/lilja/code/umbrella/customs-data-form/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at Cache.store (/Users/lilja/code/umbrella/customs-data-form/node_modules/webpack/lib/Cache.js:107:20)
    at CacheFacade.store (/Users/lilja/code/umbrella/customs-data-form/node_modules/webpack/lib/CacheFacade.js:282:15)
    at /Users/lilja/code/umbrella/customs-data-form/node_modules/webpack/lib/Compilation.js:1254:26
    at /Users/lilja/code/umbrella/customs-data-form/node_modules/webpack/lib/ContextModule.js:439:6
    at jobDone (/Users/lilja/code/umbrella/customs-data-form/node_modules/webpack/lib/FileSystemInfo.js:1676:5)
    at FileSystemInfo.createSnapshot (/Users/lilja/code/umbrella/customs-data-form/node_modules/webpack/lib/FileSystemInfo.js:1954:3)
    at /Users/lilja/code/umbrella/customs-data-form/node_modules/webpack/lib/ContextModule.js:430:31
    at /Users/lilja/code/umbrella/customs-data-form/node_modules/webpack/lib/ContextModuleFactory.js:376:7
    at done (/Users/lilja/code/umbrella/customs-data-form/node_modules/neo-async/async.js:2931:13)
    at /Users/lilja/code/umbrella/customs-data-form/node_modules/webpack/lib/ContextModuleFactory.js:354:12
    at Hook.eval [as callAsync] (eval at create (/Users/lilja/code/umbrella/customs-data-form/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [serve] Error 1
```

### Code

<details>
<summary>vue.config.js</summary>

```js
const SentryWebpackPlugin = require("@sentry/webpack-plugin");
const {gitDescribeSync} = require('git-describe');
const urls = {
    "development": "http://localhost:8000",
    "stage": "....",
    "production": "....",
};
const funnelBaseURLPrefix = {
    "development": "http://local.",
    "stage": "https://master.stage.",
    "production": "https://",
};
const gitSha = gitDescribeSync(__dirname, {
    longSemver: true,
    dirtySemver: true
})
const built = new Date().toISOString().replace('T', ' ')

process.env.VUE_APP_GIT_HASH = `SHA: ${gitSha.hash}, dirty: ${gitSha.dirty}, built: ${built}`

process.env.VUE_APP_CONNECTOR_WEB_API_URL = urls[process.env.NODE_ENV]
process.env.VUE_APP_BASE_URL = `${funnelBaseURLPrefix[process.env.NODE_ENV]}funnel.io`

let plugins = []
let publicPath = '/';

if (process.env.NODE_ENV === 'production' || process.env.NODE_ENV === 'stage') {
    publicPath = '/data-request-form/'
}
if (process.env.NODE_ENV === 'production') {
    process.env.VUE_APP_FULLSTORY_ORG = process.env.FULLSTORY_ORG
    plugins = []
}


module.exports = {
    chainWebpack: config => {
        config
            .plugin('html')
            .tap(args => {
                args[0].title = "Data Request Form";
                return args;
            })
        config.output
          .filename(`js/[name].[hash:8].js`)
          .chunkFilename(`js/[name].[hash:8].js`)
    },
    configureWebpack: {
        devServer: {
          headers: { "Access-Control-Allow-Origin": "*" }
        },
        plugins
    },
    devServer: {
      disableHostCheck: true,
    },
    publicPath: publicPath
}


```

</details>

### How Do We Reproduce?

Don't know.

### PR DESCRIPTION
**Pull request by alexander-akait**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

fixes #61

### Breaking Changes

No

### Additional Info

WIP on tests

### CODE REVIEW

**Comment by ricardogobbosouza** [comment]
I think we fixed it at the same time #63 
/cc @alexander-akait

**Comment by alexander-akait** [comment]
@ricardogobbosouza `module.resource` can be undefined + added tests

**Comment by alexander-akait** [comment]
```
const [file] = String(undefined).split('?');
console.log(file); // undefined, but it is wrong
```

**Comment by alexander-akait** [comment]
@ricardogobbosouza will you do release after merge or should I do it myself?

**Comment by ricardogobbosouza** [comment]
I'm doing

**Comment by alexander-akait** [comment]
https://www.githubstatus.com/ :disappointed:

**Comment by alexander-akait** [comment]
https://www.githubstatus.com/ :disappointed:

**Pull request merged**
