### PR TITLE
chore: use prettier defaults

### PR DESCRIPTION
**Pull request by anshumanv**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [x] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case
use prettier defaults as consistent throughout org

### Breaking Changes
no

### CODE REVIEW

**Review by alexander-akait — CHANGES_REQUESTED** [review]
Something wrong, new output is not default for prettier

**Comment by anshumanv** [comment]
strange, let me check

**Comment by ricardogobbosouza** [comment]
I don't particularly like this new style.

**Comment by ricardogobbosouza** [comment]
Can I close @alexander-akait ?
Or will it be following this pattern?

**Pull request closed without merging**
