### PR TITLE
fix: lint modules that are cached with webpack's filesystem cache

### LINKED ISSUE #130: ESLintPlugin not working consistently with cache.type = 'filesystem'
### Bug report
- OS: macOS Catalina 10.15.7
- node Version: 17.0.1
- webpack Version: 5.64.3
- eslint Version: 8.3.0
- eslint-webpack-plugin Version: 3.1.1

### Actual Behavior

With webpack cache turned on and set to 'filesystem' ESLintPlugin reports errors only after first build. If files are unchanged and build is started again ESLintPlugin will not report any errors/warnings.

### Expected Behavior

ESLintPlugin should always report same errors/warnings for same input files consistently regardless of the webpack cache.

### How Do We Reproduce?

Minimal repo: https://github.com/durad/webpack-eslint-caching-issue

Clone, run `yarn install` and then run `yarn build` twice. Warning will be shown only the first time.

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information

```
~/test/node-14-webpack-eslint * master$ yarn build
yarn run v1.22.10
$ webpack --progress --config=webpack.config.js
asset main.js 28 bytes [compared for emit] [minimized] (name: main)
./src/index.js 66 bytes [built] [code generated]

WARNING in 
/Users/dusan/test/node-14-webpack-eslint/src/index.js
  2:1  warning  Unexpected var, use let or const instead  no-var

✖ 1 problem (0 errors, 1 warning)


webpack 5.64.3 compiled with 1 warning in 358 ms
✨  Done in 0.95s.
~/test/node-14-webpack-eslint * master$ 
~/test/node-14-webpack-eslint * master$ 
~/test/node-14-webpack-eslint * master$ 
~/test/node-14-webpack-eslint * master$ yarn build
yarn run v1.22.10
$ webpack --progress --config=webpack.config.js
asset main.js 28 bytes [compared for emit] [minimized] (name: main)
cached modules 66 bytes [cached] 1 module
webpack 5.64.3 compiled successfully in 209 ms
✨  Done in 0.80s.
~/test/node-14-webpack-eslint * master$ 
~/test/node-14-webpack-eslint * master$ 
~/test/node-14-webpack-eslint * master$ 
```

Same happens with both development and production mode.

### PR DESCRIPTION
**Pull request by facugaich**
This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [x] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

If webpack is setup with cache type `filesystem`, the `succeedModule` hook is not called for cached modules and no linting is run for them. Tap the `stillValidModule` hook to lint cached modules.

Note regarding testing, I tried several strategies but the only one that I managed to get working was to create two different compilers and have the second one pickup the cache left by the first one.

Fixes #130

### CODE REVIEW

**Review by alexander-akait — DISMISSED** [review]

**Comment by instagibb** [comment]
Is this gonna be reviewed/merged anytime soon? Really keen to see this in a release

**Comment by ricardogobbosouza** [comment]
Sorry for the delay, my considerations:

1. The lint will run again on the cached files, impairs the performance.
2. The plugin should retrieve errors and warnings from cached files as @alexander-akait  mentioned here https://github.com/webpack-contrib/eslint-webpack-plugin/issues/130#issuecomment-985487732
3. I'm going to merge this PR because it solves this problem, but we need to deal with the performance

**Comment by facugaich** [comment]
@ricardogobbosouza Thank you!

Re: performance, could we use ESLint's own `cache` option for that? It seems like it would work for the non-threaded case at least, and you've mentioned that the threaded impl should be deprecated anyways in #143

**Comment by yoyo837** [comment]
This changes caused Hot Module Replacement build to be very slow after save files.

**Pull request merged**
